### ISSUE TITLE
Add current developments beyond W3C?

### ISSUE THREAD

**Issue by rolfkleef** [StanimirIglev/awesome-xml#8]
The official W3C standards seem "frozen in time" around 2005-2010, but several standards are still being developed further, for instance as community groups:

- [XProc 3.0+: An XML Pipeline Language (draft)](https://spec.xproc.org/master/head/xproc/) and [XProc 3.0+: Standard Step Library (draft)](https://spec.xproc.org/master/head/steps/)
   - Book: [XProc 3.0 Programmer Reference](https://xmlpress.net/publications/xproc-3-0/)
- [XSL Transformations (XSLT) Version 3.0](https://www.w3.org/TR/xslt-30/) and [XSL Transformations (XSLT) Version 4.0 (draft)](https://qt4cg.org/specifications/xslt-40/Overview.html)
- ...etc

It seems to make most sense to add such links as versions in the XML family section, to help people find more contemporary versions?

**Comment by StanimirIglev** [comment]
Hey Rolf,

Thank you for the suggestions!

I agree that it is essential to help people find the latest developments/drafts. However, I want to ensure a clear distinction between official W3C standards/recommendations and drafts that are still under development.

I propose creating a separate section for actively-developed drafts. This way, we can provide visibility to the latest work without confusing drafts with the finalized standards. I believe this approach will maintain the clarity of the repository while acknowledging ongoing developments in the XML community.

To address the rest of your points:
- The suggested book can most certainly be added to the books section. 
- The XSLT 3.0 is linked in The XML Family section. As you can see, the link leads to the XSLT cover page that lists all specification versions.

Thank you again for your input. If you have any further suggestions or concerns, please feel free to share!

**Comment by rolfkleef** [comment]
hi Stan,

I agree with adding a section for "active development", or perhaps a section under "community". It could be a way to add other current developments, like the [Invisible XML Specification](https://www.w3.org/community/reports/ixml/ixml/).

I'm still trying to navigate how W3C actually works, between endorsed standards and community initiatives :-)

**Comment by StanimirIglev** [comment]
Sounds like a plan!

I will add a Drafts and Community Specifications section.
Looking forward to all the awesomeness that will end up there.
