### ISSUE TITLE
Add QT4CG 4.0 working group to https://github.com/StanimirIglev/awesome-xml?tab=readme-ov-file#drafts-and-community-advances

### ISSUE THREAD

**Issue by martin-honnen** [StanimirIglev/awesome-xml#9]
There is ongoing work on XPath 4, XQuery 4 and XSLT 4, see https://qt4cg.org/ and https://www.w3.org/community/xslt-40/. I think this should be added to https://github.com/StanimirIglev/awesome-xml?tab=readme-ov-file#drafts-and-community-advances.

**Comment by StanimirIglev** [comment]
That is an excellent suggestion. I will make sure to add it as soon as possible.
